/*
 * Generated by gdbus-codegen 2.32.4. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifndef __MYAPP_GENERATED_H__
#define __MYAPP_GENERATED_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for net.Corp.MyApp.Frobber */

#define MY_APP_TYPE_FROBBER (my_app_frobber_get_type ())
#define MY_APP_FROBBER(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MY_APP_TYPE_FROBBER, MyAppFrobber))
#define MY_APP_IS_FROBBER(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MY_APP_TYPE_FROBBER))
#define MY_APP_FROBBER_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), MY_APP_TYPE_FROBBER, MyAppFrobberIface))

struct _MyAppFrobber;
typedef struct _MyAppFrobber MyAppFrobber;
typedef struct _MyAppFrobberIface MyAppFrobberIface;

struct _MyAppFrobberIface
{
  GTypeInterface parent_iface;



  gboolean (*handle_hello_world) (
    MyAppFrobber *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_greeting);

  gboolean  (*get_verbose) (MyAppFrobber *object);

  void (*notification) (
    MyAppFrobber *object,
    const gchar *arg_icon_blob,
    gint arg_height,
    const gchar *const *arg_messages);

};

GType my_app_frobber_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *my_app_frobber_interface_info (void);
guint my_app_frobber_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void my_app_frobber_complete_hello_world (
    MyAppFrobber *object,
    GDBusMethodInvocation *invocation,
    const gchar *response);



/* D-Bus signal emissions functions: */
void my_app_frobber_emit_notification (
    MyAppFrobber *object,
    const gchar *arg_icon_blob,
    gint arg_height,
    const gchar *const *arg_messages);



/* D-Bus method calls: */
void my_app_frobber_call_hello_world (
    MyAppFrobber *proxy,
    const gchar *arg_greeting,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean my_app_frobber_call_hello_world_finish (
    MyAppFrobber *proxy,
    gchar **out_response,
    GAsyncResult *res,
    GError **error);

gboolean my_app_frobber_call_hello_world_sync (
    MyAppFrobber *proxy,
    const gchar *arg_greeting,
    gchar **out_response,
    GCancellable *cancellable,
    GError **error);



/* D-Bus property accessors: */
gboolean my_app_frobber_get_verbose (MyAppFrobber *object);
void my_app_frobber_set_verbose (MyAppFrobber *object, gboolean value);


/* ---- */

#define MY_APP_TYPE_FROBBER_PROXY (my_app_frobber_proxy_get_type ())
#define MY_APP_FROBBER_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MY_APP_TYPE_FROBBER_PROXY, MyAppFrobberProxy))
#define MY_APP_FROBBER_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), MY_APP_TYPE_FROBBER_PROXY, MyAppFrobberProxyClass))
#define MY_APP_FROBBER_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), MY_APP_TYPE_FROBBER_PROXY, MyAppFrobberProxyClass))
#define MY_APP_IS_FROBBER_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MY_APP_TYPE_FROBBER_PROXY))
#define MY_APP_IS_FROBBER_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), MY_APP_TYPE_FROBBER_PROXY))

typedef struct _MyAppFrobberProxy MyAppFrobberProxy;
typedef struct _MyAppFrobberProxyClass MyAppFrobberProxyClass;
typedef struct _MyAppFrobberProxyPrivate MyAppFrobberProxyPrivate;

struct _MyAppFrobberProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  MyAppFrobberProxyPrivate *priv;
};

struct _MyAppFrobberProxyClass
{
  GDBusProxyClass parent_class;
};

GType my_app_frobber_proxy_get_type (void) G_GNUC_CONST;

void my_app_frobber_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
MyAppFrobber *my_app_frobber_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
MyAppFrobber *my_app_frobber_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void my_app_frobber_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
MyAppFrobber *my_app_frobber_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
MyAppFrobber *my_app_frobber_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define MY_APP_TYPE_FROBBER_SKELETON (my_app_frobber_skeleton_get_type ())
#define MY_APP_FROBBER_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MY_APP_TYPE_FROBBER_SKELETON, MyAppFrobberSkeleton))
#define MY_APP_FROBBER_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), MY_APP_TYPE_FROBBER_SKELETON, MyAppFrobberSkeletonClass))
#define MY_APP_FROBBER_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), MY_APP_TYPE_FROBBER_SKELETON, MyAppFrobberSkeletonClass))
#define MY_APP_IS_FROBBER_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MY_APP_TYPE_FROBBER_SKELETON))
#define MY_APP_IS_FROBBER_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), MY_APP_TYPE_FROBBER_SKELETON))

typedef struct _MyAppFrobberSkeleton MyAppFrobberSkeleton;
typedef struct _MyAppFrobberSkeletonClass MyAppFrobberSkeletonClass;
typedef struct _MyAppFrobberSkeletonPrivate MyAppFrobberSkeletonPrivate;

struct _MyAppFrobberSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  MyAppFrobberSkeletonPrivate *priv;
};

struct _MyAppFrobberSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType my_app_frobber_skeleton_get_type (void) G_GNUC_CONST;

MyAppFrobber *my_app_frobber_skeleton_new (void);


G_END_DECLS

#endif /* __MYAPP_GENERATED_H__ */
